// Generated by https://quicktype.io
// /api/items?search=string

import { Author } from './IAuthor'

export interface IInternalSearchResponse {
  author: Author
  categories: string[]
  items: Item[]
}

export interface Item {
  id: string
  title: string
  price: Price
  picture: string
  condition: string
  free_shipping: boolean
}

export interface Price {
  currency: string
  amount: number
  decimals: number
}
